# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jack Kamm's Homepage
name: Jack Kamm
#email: jack.kamm@czbiohub.org
description: > # this means to ignore newlines until "baseurl:"
  Statistics, genetics, emacs.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jackkamm
github_username:  jackkamm
mastodon_username: snackematician@mastodon.social
orcid: 0000-0003-2412-756X

# Build settings
markdown: kramdown
